### ISSUE TITLE
Minecraft 1.21 incompatible?

### ISSUE THREAD

**Issue by lavagaster-afk** [FalseMSP/SoundPhysicsPerfected#72]
### Mod Loader

Fabric

### Mod Version

1.10.3

### Game Version

1.21

### What is the bug?

Fabric tells me that it requires a newer version of YACL but the newer versions dont work on minecraft 1.21 its just for later versions

### Steps to Reproduce

just use minecraft 1.21 fabric with the latest YACL version and latest SPP version for 1.21

**Comment by FalseMSP** [comment]
looks like a yacl issue 😔 
(though I do suppose it's on me too bc of the minimum requirement for yacl)

**Comment by Tsoccerguy3** [comment]
Does not support 1.21.8 Neoforge v36 .Crash on startup

The game crashed: unexpected error
Error: java.lang.NoClassDefFoundError: Could not initialize class com.redsmods.sound_physics_perfected.config.Config

**Comment by lavagaster-afk** [comment]
Will the issue get fixed?

**Comment by FalseMSP** [comment]
> Does not support 1.21.8 Neoforge v36 .Crash on startup
> 
> The game crashed: unexpected error Error: java.lang.NoClassDefFoundError: Could not initialize class com.redsmods.sound_physics_perfected.config.Config

make a separate issue
currently still busy so I'll fix it in a bit

**Comment by FalseMSP** [comment]
> Will the issue get fixed?

yes
I'm busy IRL rn 
will fix soon though

**Comment by FalseMSP** [comment]
> Does not support 1.21.8 Neoforge v36 .Crash on startup
> 
> The game crashed: unexpected error Error: java.lang.NoClassDefFoundError: Could not initialize class com.redsmods.sound_physics_perfected.config.Config

i looked into it
make sure u don't have sound physics remasterd, if u do, delete it :)
if u don't
create an issue and list the mods u have

**Comment by Tellinq** [comment]
Am I stupid or something?

Shouldn’t the latest 3.7.1 work already for 1.21-1.21.1? (according to Modrinth)

<img width="1179" height="866" alt="Image" src="https://github.com/user-attachments/assets/dd9bb769-2324-4a7c-b5ae-e6ed14714736" />

**Comment by FalseMSP** [comment]
> Am I stupid or something?
> 
> Shouldn’t the latest 3.7.1 work already for 1.21-1.21.1? (according to Modrinth)
> <img alt="Image" width="1179" height="866" src="https://private-user-images.githubusercontent.com/59412384/482874650-dd9bb769-2324-4a7c-b5ae-e6ed14714736.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzNDc4ODksIm5iZiI6MTc1NjM0NzU4OSwicGF0aCI6Ii81OTQxMjM4NC80ODI4NzQ2NTAtZGQ5YmI3NjktMjMyNC00YTdjLWI1YWUtZTZlZDE0NzE0NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI4VDAyMTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNTg4YzQ4Mzk5YjE5NjBkOGVjZDgwOTBhNmJhYzMzNzhmMTI3MWVhZmNiOWMyM2YzYzY0NWY0ODkzZTkzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EoDoBkbBPpenMJ8A2I1edQ1LkpOlVGjpWiqRnPq9PRI">

it requires a fabric api version that doesn't exist for 1.21

**Comment by FalseMSP** [comment]
this im p sure works again, or it was a problem on yacl's part
